const items = [
    {
        id: '1',
        title: 'AJAYCO Wooden Craft Handmade Tabletop Laptop Stand with Angle Adjustable | Laptop Foldable Stand | Portable Wooden Laptop Stand',
        uri: [
            { "image": require('../assets/images/LaptopStand1.png') },
            { "image": require('../assets/images/LaptopStand2.png') },
            { "image": require('../assets/images/LaptopStand3.png') },
            { "image": require('../assets/images/LaptopStand4.png') },
            { "image": require('../assets/images/LaptopStand5.png') },
            { "image": require('../assets/images/LaptopStand6.png') },
            { "image": require('../assets/images/LaptopStand7.jpg') },
            { "image": require('../assets/images/LaptopStand8.png') },
            { "image": require('../assets/images/LaptopStand9.png') },
        ],
        price: 1249.00,
        sku: "N/A",
        availability: "100 In Stock",
        category: "Laptop Stand",
        material: "Australian Pine Wood - Natural ( light Yellow )",
        size: "9.8 × 12.6 × 0.8 in",
        weight: "740 lbs",
        description: "AJAYCO Wooden Craft Handmade Tabletop Laptop Stand with Angle Adjustable | Laptop Foldable Stand | Tablet Stand | Portable \n Wooden Laptop Stand Wood Type : Australian Pine Wood \n Wood Type : Australian Pine Wood \n Color : Natural ( light Yellow ) \n Size : Universal Laptop Stand Perfect for 10 inch, 11 inch, 13 inch, 15.6 inch, 17 inch laptops \n Actual Size : 9.8 inch X 12.6 inch X 0.8 inch \n Packing Box Size : 10.5 X 1.75 X 13.5 inch \n Weight : 740 Gms ( Including Packing Box, Only Stand Weight 640gms )",
        additionalinfo: "Weight - 740 lbs \n Dimensions - 9.8 × 12.6 × 0.8 in",
        tags: "computer stand, lapotp stand, laptop tabletop stand, tablet stand, Wooden Laptop Stand.",
        reviews: "There are no reviews yet. \n Only logged in customers who have purchased this product may leave a review."
    },
    {
        id: '2',
        title: 'Easel Stand For Embroidery Hoop | Photo Frame | Picture Card',
        uri: [
            { "image": require('../assets/images/12-inch-Easel-Stand1.png') },
            { "image": require('../assets/images/12-inch-Easel-Stand2.jpg') },
        ],
        price: 50.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Embroidery Hoop Stand",
        material: "Indian Pine Wood & Brass",
        size: "6inch, 8inch, 12inch - 6 Pcs in a Packet",
        weight: "",
        description: "This wooden stand is specially design to display Cross-stich & Embroidery Hoop art. You can Easily adjust brass screw for proper standing angle adjustment.",
        additionalinfo: "",
    },
    {
        id: '3',
        title: 'Embroidery Hoop & Frame Holder Stand for Cross Stitch 360′ Rotatable',
        uri: [
            { "image": require('../assets/images/Dual-Hoop-Holder-Stand.png') },
            { "image": require('../assets/images/Dual-Hoop-Holder-Stand.png') },
        ],
        price: 1350.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Embroidery Hoop Stand",
        material: "Wood & Stainless Steel All Screw with L-key & Heavy Wing Nutts",
        size: "7.32 × 4.33 × .78 in",
        weight: "1.5 lbs",
        description: "Dual Holder Embroidery Hoop Stand. You Can Rotate or Adjust Hoop/frame 360 Degree.",
        additionalinfo: "",
    },
    {
        id: '4',
        title: 'Oval Shape Embroidery Frame | Hoop',
        uri: [
            { "image": require('../assets/images/OvelShapeHoopWithBrassHook.png') },
            { "image": require('../assets/images/OvelShapeHoopWithBrassHook.png') },
        ],
        price: 90.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Ovel Shape Embroidery Hoop",
        material: "Indian Pine Exportable Wood",
        size: "6 inch, 8 inch, 10 inch, 12 inch, 14 inch : 4+4-Layer",
        weight: "",
        description: "This Wooden Embroidery Hoop is must-have for every embroiderer. You can easily stretch your fabric and keep it tightly secured into place with the help of the screw given. Another use of it is in paintings, as the fabric is nice and tight, you can easily paint on it. With brass screw & Nut Also waterproof.",
        additionalinfo: "",
    },
    {
        id: '5',
        title: 'Rectangular Wooden Embroidery Hoop Stand | Props',
        uri: [
            { "image": require('../assets/images/Sqaure-Hoop-Stand-Single-Line.png') },
            { "image": require('../assets/images/Sqaure-Hoop-Stand-Single-Line.png') },
        ],
        price: 55.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Embroidery Hoop Stand",
        material: "100% Pine Wood",
        size: "10x8x2 cm - Hoop standing Gap: 1×9 cm - 6 nos in a packet. (Per nos Rate – 55/-)",
        weight: "72 gms",
        description: "Wooden Embroidery Hoop Stand ",
        additionalinfo: "",
    },
    {
        id: '6',
        title: 'Round Shape Embroidery Frame | Hoop with Brass Hook',
        uri: [
            { "image": require('../assets/images/Round-Hoop-With-Brass-Hook-Website.png') },
            { "image": require('../assets/images/Round-Hoop-With-Brass-Hook-Website.png') },
        ],
        price: 35.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Round Shape Embroidery Hoop",
        material: "Indian Pine Exportable Wood",
        size: "3 inch, 4 inch, 6 inch, 8 inch, 10 inch, 12 inch, 14 inch : 4+4-Layer",
        weight: "",
        description: "Export Quality Round Shape Embroidery Hoop With Bras Hook. This Wooden Embroidery Hoop is must-have for every embroiderer. You can easily stretch your fabric and keep it tightly secured into place with the help of the screw given. Another use of it is in paintings, as the fabric is nice and tight, you can easily paint on it.",
        additionalinfo: "",
    },
    {
        id: '7',
        title: 'Round Shape Embroidery Frame | Hoop with Iron Hook',
        uri: [
            { "image": require('../assets/images/Round-Shape-Embroidery-Hoop-with-Iron-Hook.png') },
            { "image": require('../assets/images/Round-Shape-Embroidery-Hoop-with-Iron-Hook.png') },
        ],
        price: 20.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Round Shape Embroidery Hoop",
        material: "Indian Pine Exportable Wood",
        size: "4 inch, 5 inch, 6 inch, 7 inch, 8 inch, 9 inch, 10 inch, 12 inch, 14 inch : 4+4-Layer",
        weight: "1 lbs",
        description: "This Wooden Embroidery Hoop is must-have for every embroiderer. You can easily stretch your fabric and keep it tightly secured into place with the help of the screw given. Another use of it is in paintings, as the fabric is nice and tight, you can easily paint on it.",
        additionalinfo: "",
    },
    {
        id: '8',
        title: 'Round Shape Hoop Without Hook',
        uri: [
            { "image": require('../assets/images/RoundHoopWithoutHook.png') },
            { "image": require('../assets/images/RoundHoopWithoutHook.png') },
        ],
        price: 36.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Round Hoop Without Hook",
        material: "Indian Pine Exportable Wood",
        size: "6 inch, 8 inch, 10 inch, 12 inch, 14 inch",
        weight: "",
        description: "Round Hoop without Screw | Hook",
        additionalinfo: "",
    },
    {
        id: '9',
        title: 'Square Shape Embroidery Frame | Hoop',
        uri: [
            { "image": require('../assets/images/SquareShapeEmbroideryHoop.jpg') },
            { "image": require('../assets/images/SquareShapeEmbroideryHoop.jpg') },
        ],
        price: 120.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Square Shape Embroidery Hoop",
        material: "Indian Pine Exportable Wood",
        size: "8 inch, 10 inch, 12 inch, 14 inch : 4+4-Layer",
        weight: "",
        description: "This Wooden Embroidery Hoop is must-have for every embroiderer. You can easily stretch your fabric and keep it tightly secured into place with the help of the screw given. Another use of it is in paintings, as the fabric is nice and tight, you can easily paint on it. It is with brass screw & Nut Also waterproof.",
        additionalinfo: "",
    },
    {
        id: '10',
        title: 'Triangle Shape Embroidery Frame | Hoop With Brass Hook',
        uri: [
            { "image": require('../assets/images/TringleShapeEmbroideryHoop.png') },
            { "image": require('../assets/images/TringleShapeEmbroideryHoop.png') },
        ],
        price: 120.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Triangle Shape Embroidery Hoop",
        material: "Indian Pine Exportable Wood",
        size: "8 inch, 10 inch, 12 inch, 14 inch : 4+4-Layer",
        weight: "",
        description: "This Wooden Embroidery Hoop is must-have for every embroiderer. You can easily stretch your fabric and keep it tightly secured into place with the help of the screw given. Another use of it is in paintings, as the fabric is nice and tight, you can easily paint on it. It is with brass screw & Nut Also waterproof.",
        additionalinfo: "",
    },
    {
        id: '11',
        title: 'Triangle Shape Embroidery Hoop Display Stand/Props',
        uri: [
            { "image": require('../assets/images/Triangle-Hoop-Stand-1.png') },
            { "image": require('../assets/images/Triangle-Hoop-Stand-1.png') },
        ],
        price: 85.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Embroidery Hoop Stand",
        material: "100% Pine Wood",
        size: "10x11x2 cm - Hoop standing Gap: 1×9 cm - 6 nos in a packet. (Per nos Rate – 80/-)",
        weight: "72 gms",
        description: "Embroidery Hoop Stand / Display Holder – A must have on your craft table to display your craft without blue tag or the need to hang on the wall.",
        additionalinfo: "",
    },
    {
        id: '12',
        title: 'Wooden Embroidery Lap Adjustable Hoop & Frame Holder Stand-1 Set (3 Pieces)',
        uri: [
            { "image": require('../assets/images/Hoop-Holder-Stand-2.png') },
            { "image": require('../assets/images/Hoop-Holder-Stand-2.png') },
        ],
        price: 1150.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Embroidery Hoop Stand",
        material: "Wood & Stainless Steel All Screw with L-key & Heavy Wing Nutts",
        size: "You Can Rotate or Adjust Hoop/frame 360 Degree. - 1 Set ( 3 Pieces)",
        weight: "",
        description: "Single Holder Embroidery Hoop Stand",
        additionalinfo: "",
    },
    {
        id: '13',
        title: 'Wooden Hoops for Dream Catchers | Wedding Decor | Wall Hanging Craft',
        uri: [
            { "image": require('../assets/images/HoopForDreamcatcher.png') },
            { "image": require('../assets/images/HoopForDreamcatcher.png') },
        ],
        price: 24.00,
        sku: "N/A",
        availability: "In Stock",
        category: "Round Internal Embroidery Hoop.",
        material: "Indian Pine Exportable Wood",
        size: "6 inch, 8 inch, 10 inch, 12 inch - 4 Layer(Bonding With Formaldehyde Free Adhesive)",
        weight: "",
        description: "Round Shape Wooden Hoops for Dream Catchers. This Wooden Dream Catcher Hoop is must-have for every embroiderer.",
        additionalinfo: "",
    },
  ];

  export const getProducts = () => {
    return items;
    
}